In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import numpy as np



cat_breeds = pd.read_csv('cat_breeds_clean.csv',sep=",")
display(cat_breeds)
imputer = SimpleImputer(strategy='median')  # para rellenar los huecos de datos vacios con la mediana

# Simplemente lo ves con tus propios ojos cuales faltan
# convierte todo lo de la columna "Latitude" que sea "-" y lo convierte a NaN (Not a number)
cat_breeds["Latitude"]=cat_breeds["Latitude"].apply(lambda x: np.nan if x == "-" else x)

# Suma todos los NaN
countNaN = cat_breeds.isna().sum()
print("=== Todos los countNaN ===")
print(countNaN)


# Codifica "Gender" 
Gender = cat_breeds["Gender"].to_numpy()    # la extrae de esta manera para que las biblios puedan trabajar con ella
labelEncoder=LabelEncoder()
Gender = labelEncoder.fit_transform(Gender)     # hace male = 0 y female = 1 y unknown = 2 (por ejemplo)
# rellena los huecos vacios con la mediana (imputer declarado al principio)
# reshape: lo pone todo en una sola columna(1) y pone tantas filas como sean necesarias(-1)
Gender=imputer.fit_transform(Gender.reshape(-1, 1))     
cat_breeds["Gender"] = Gender   # sobreescribe en el df original

# creas un imputer pero esta vez con la media
imputerMean = SimpleImputer(strategy='mean')
Latitude=cat_breeds["Latitude"].to_numpy()
Latitude=imputerMean.fit_transform(Latitude.reshape(-1, 1))
cat_breeds["Latitude"] = Latitude

countNaN = cat_breeds.isna().sum()
print("=== LOS COUNTNAN NUEVAMENTE ===")
print(countNaN)
display(cat_breeds.head())

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3,female,False,19,2.0,white,solid,blue,False,wet,46,16,France,NaN,5.369780
1,Angora,0.33,4,male,False,19,2.5,white,solid,blue,False,wet,48,16,France,43.611660,3.877710
2,Angora,0.50,6,male,False,20,2.8,black,solid,green,False,wet,41,11,France,44.837789,-0.579180
3,Angora,0.50,6,female,False,21,3.0,white,solid,blue,False,wet,24,8,France,43.611660,3.877710
4,Angora,0.50,6,male,False,21,3.0,red/cream,tabby,green,False,wet,51,10,France,48.864716,2.349014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,Maine coon,0.17,2,female,False,15,1.2,white,solid,blue,False,wet,35,20,UK,51.507351,-0.127758
1067,Maine coon,0.17,2,female,False,17,1.0,black,bicolor,blue,False,wet,36,19,UK,51.507351,-0.127758
1068,Maine coon,0.17,2,male,False,14,0.7,red/cream,tabby,blue,False,wet,20,20,UK,51.507351,-0.127758
1069,Maine coon,0.17,2,male,False,16,1.1,red/cream,tabby,green,False,wet,34,19,UK,52.486244,-1.890401
1070,Maine coon,0.17,2,female,False,15,1.1,red/cream,solid,blue,False,wet,39,20,UK,51.507351,-0.127758

=== Todos los countNaN ===
Breed                      0
Age_in_years               0
Age_in_months              0
Gender                     3
Neutered_or_spayed         0
Body_length                0
Weight                     0
Fur_colour_dominant        0
Fur_pattern                0
Eye_colour                 0
Allowed_outdoor            0
Preferred_food             0
Owner_play_time_minutes    0
Sleep_time_hours           0
Country                    0
Latitude                   2
Longitude                  0
dtype: int64
=== LOS COUNTNAN NUEVAMENTE ===
Breed                      0
Age_in_years               0
Age_in_months              0
Gender                     0
Neutered_or_spayed         0
Body_length                0
Weight                     0
Fur_colour_dominant        0
Fur_pattern                0
Eye_colour                 0
Allowed_outdoor            0
Preferred_food             0
Owner_play_time_minutes    0
Sleep_time_hours           0
Country                    0
Latitude                   0
Longitude                  0
dtype: int64

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3,0.0,False,19,2.0,white,solid,blue,False,wet,46,16,France,44.437828,5.369780
1,Angora,0.33,4,1.0,False,19,2.5,white,solid,blue,False,wet,48,16,France,43.611660,3.877710
2,Angora,0.50,6,1.0,False,20,2.8,black,solid,green,False,wet,41,11,France,44.837789,-0.579180
3,Angora,0.50,6,0.0,False,21,3.0,white,solid,blue,False,wet,24,8,France,43.611660,3.877710
4,Angora,0.50,6,1.0,False,21,3.0,red/cream,tabby,green,False,wet,51,10,France,48.864716,2.349014

In [2]:
#Label Encoding

# Neutered_or_spayed: True / False
Neutered_or_spayed = cat_breeds["Neutered_or_spayed"]                   # extraer columna
Neutered_or_spayed_NP = Neutered_or_spayed.to_numpy()                   # convertir a formato matematico
Neutered_or_spayed = labelEncoder.fit_transform(Neutered_or_spayed_NP)     # transformar palabras a numeros
cat_breeds["Neutered_or_spayed"] = Neutered_or_spayed                   

# Allowed_outdoor: True / False
Allowed_outdoor = cat_breeds["Allowed_outdoor"]
Allowed_outdoor_NP = Allowed_outdoor.to_numpy()
Allowed_outdoor_NP = labelEncoder.fit_transform(Allowed_outdoor_NP)
cat_breeds["Allowed_outdoor"] = Allowed_outdoor_NP

# Preferred_food: dry /wet
Preferred_food = cat_breeds["Preferred_food"]
Preferred_food_NP = Preferred_food.to_numpy()
Preferred_food_NP = labelEncoder.fit_transform(Preferred_food_NP)
cat_breeds["Preferred_food"] = Preferred_food_NP




# ONE HOT Encoding.
# sparse_output = False . Es para que sea una matriz de 1 y 0 en vez de un formato comprimido raro
encoder = OneHotEncoder(sparse_output=False)

Fur_colour_dominant=cat_breeds["Fur_colour_dominant"]                                       # extraer columna
Fur_colour_dominant_NP = Fur_colour_dominant.to_numpy()                                     # convertir en formato matemático
Fur_colour_dominant_OHE = encoder.fit_transform(Fur_colour_dominant_NP.reshape(-1, 1))      # crea la nueva matriz de 1 y 0
cat_breeds = cat_breeds.drop("Fur_colour_dominant",axis=1)                                  # borra la columa original

Fur_pattern=cat_breeds["Fur_pattern"]
Fur_pattern_NP = Fur_pattern.to_numpy()
Fur_pattern_NP_OHE = encoder.fit_transform(Fur_pattern_NP.reshape(-1, 1))
cat_breeds = cat_breeds.drop("Fur_pattern",axis=1)

Eye_colour=cat_breeds["Eye_colour"]
Eye_colour_NP = Eye_colour.to_numpy()
Eye_colour_NP_OHE = encoder.fit_transform(Eye_colour_NP.reshape(-1, 1))
cat_breeds = cat_breeds.drop("Eye_colour",axis=1)

Country=cat_breeds["Country"]
Country_NP = Country.to_numpy()
Country_NP_OHE = encoder.fit_transform(Country_NP.reshape(-1, 1))
cat_breeds = cat_breeds.drop("Country",axis=1)

display(cat_breeds.head())

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Latitude,Longitude
0,Angora,0.25,3,0.0,0,19,2.0,0,1,46,16,44.437828,5.369780
1,Angora,0.33,4,1.0,0,19,2.5,0,1,48,16,43.611660,3.877710
2,Angora,0.50,6,1.0,0,20,2.8,0,1,41,11,44.837789,-0.579180
3,Angora,0.50,6,0.0,0,21,3.0,0,1,24,8,43.611660,3.877710
4,Angora,0.50,6,1.0,0,21,3.0,0,1,51,10,48.864716,2.349014

In [3]:
# Coges la Y (el objetivo) y lo borras de la tabla principal
Y = cat_breeds["Breed"].to_numpy()
cat_breeds=cat_breeds.drop("Breed",axis=1)

# Coges la X como las pistas o las características
X = cat_breeds.to_numpy()
print(X.shape)

# Le pones a la X todo lo que has hecho con HOT ENCODING
X = np.hstack((X,Fur_colour_dominant_OHE,Fur_pattern_NP_OHE,Eye_colour_NP_OHE,Country_NP_OHE))
print(X.shape)

(1071, 12)
(1071, 33)

MVP

In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Escalar para que todo la media 0 y desviacion tipica 1
scaler = StandardScaler()
X = scaler.fit_transform(X)                 # escala las características
Y = labelEncoder.fit_transform(Y)           # escala el objetivo
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=0)       # divide en 25% para el examen final

print("y_train")
print(y_train)
print("X_train.shape")
print(X_train.shape)
print("X_test.shape")
print(X_test.shape)
print("y_train.shape")
print(y_train.shape)
print("y_test.shape")
print(y_test.shape)

y_train
[0 0 1 2 0 1 2 2 2 0 2 0 2 0 0 2 1 1 2 1 0 1 2 2 1 2 0 2 2 0 0 0 1 0 1 1 0
 1 2 2 1 2 0 0 0 2 0 2 2 2 0 0 2 0 1 2 1 1 2 2 0 0 2 1 2 2 1 1 1 0 2 1 1 1
 2 2 0 2 1 0 0 2 0 2 1 2 0 2 0 2 2 2 0 0 0 0 1 1 0 1 0 2 1 1 2 1 2 2 0 0 2
 1 2 1 1 1 1 0 0 0 1 2 0 1 0 0 1 0 2 2 2 2 1 0 2 0 1 2 0 2 1 2 1 1 1 0 0 0
 1 0 0 0 1 0 2 1 0 1 0 2 2 1 1 2 2 1 2 0 2 0 1 1 0 2 2 1 1 0 2 0 0 2 0 1 2
 2 1 0 2 2 1 1 0 1 1 2 2 2 2 2 0 2 0 2 2 2 0 0 2 0 0 0 2 1 2 1 2 0 2 1 2 1
 1 0 2 1 1 1 1 2 0 1 0 0 0 0 0 1 2 1 1 2 2 2 2 0 2 0 1 0 2 2 0 2 1 0 2 2 1
 2 0 1 1 2 2 1 2 0 1 1 2 0 2 0 1 1 0 1 1 0 1 2 2 0 2 1 1 1 0 1 2 1 2 2 1 0
 0 1 2 0 2 2 0 2 1 0 0 2 2 0 1 1 1 2 1 0 2 0 0 1 0 2 1 0 0 0 0 2 2 2 1 2 0
 2 1 2 2 0 0 1 2 2 2 2 2 0 2 1 2 1 1 1 2 0 1 0 2 1 0 0 2 1 1 0 0 2 2 0 2 0
 1 2 2 2 2 1 2 1 0 1 1 1 2 2 2 2 0 1 1 1 1 2 2 1 2 2 2 1 1 2 2 1 0 2 2 1 0
 2 0 1 2 1 2 1 2 1 2 2 0 2 1 1 1 2 0 2 1 2 2 2 1 2 1 2 2 2 1 2 0 1 1 1 1 0
 1 1 0 2 1 1 0 0 1 2 2 2 0 0 2 1 2 0 0 0 1 2 2 1 1 1 1 2 1 2 0 1 0 2 2 2 2
 1 2 1 2 0 2 2 1 1 1 0 1 1 1 0 2 0 1 2 0 0 1 2 1 0 0 1 1 2 2 2 2 0 0 1 2 0
 2 1 1 2 2 2 0 2 0 0 0 1 0 0 0 1 2 1 0 2 2 2 1 0 1 2 1 1 1 2 2 2 2 0 1 2 2
 2 2 2 1 2 0 0 2 2 2 2 2 2 2 2 2 2 0 2 0 0 1 0 2 2 0 1 0 0 2 0 1 1 0 2 1 2
 2 2 1 1 1 1 0 1 1 0 2 1 1 0 1 0 0 0 0 1 2 2 2 1 1 0 2 0 2 2 2 1 2 0 1 1 2
 2 0 1 1 2 0 2 0 0 1 2 2 1 1 1 1 1 0 1 2 1 0 2 2 0 0 0 1 2 0 2 0 0 2 0 1 0
 0 2 1 1 0 0 2 1 0 2 2 1 0 1 0 2 0 2 1 1 2 1 1 0 2 1 1 2 1 2 2 2 1 2 2 0 2
 0 0 0 2 0 1 1 1 2 1 2 2 2 2 0 2 0 2 0 2 2 0 2 0 2 2 1 0 0 2 2 2 1 2 1 2 0
 0 1 2 0 2 1 0 2 2 1 0 2 2 1 0 2 1 1 0 2 2 0 2 0 2 1 2 0 0 2 1 1 2 2 1 2 2
 2 0 0 2 1 2 2 0 2 0 2 1 2 0 0 1 2 1 1 1 0 2 2 2 1 2]
X_train.shape
(803, 33)
X_test.shape
(268, 33)
y_train.shape
(803,)
y_test.shape
(268,)

In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Tamaño de X_train:", X_train.shape)
print("Tamaño de y_train:", y_train.shape)

# 1. Crear el modelo (Usamos los mismos parámetros que tu profesor puso antes)
mlp = MLPClassifier(
    hidden_layer_sizes=(30, 10), # Dos capas ocultas con 30 y 10 neuronas
    activation='relu',           # Función no lineal
    max_iter=7000,               # Límite de épocas de estudio
    alpha=0.01,                  # Regularización (evita el sobreajuste)
    learning_rate_init=0.001,    # Velocidad de aprendizaje
    random_state=0               # Semilla para que el resultado sea siempre el mismo
)

# 2. Entrenar la Red Neuronal
print("\nEntrenando la red neuronal... (esto puede tardar unos segundos)")
mlp.fit(X_train, y_train)

# 3. Hacer las predicciones con el conjunto de examen (test)
y_pred = mlp.predict(X_test)

# 4. Evaluar los resultados
accuracy = accuracy_score(y_test, y_pred)

print("\n=== RESULTADOS DEL MODELO ===")
print("Accauricy: ", accuracy)
print(f"Accuracy (Porcentaje de acierto): {accuracy * 100:.2f}%\n")

# Extra: Añadimos la matriz de confusión y el reporte detallado que siempre viene bien
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

Tamaño de X_train: (803, 33)
Tamaño de y_train: (803,)

Entrenando la red neuronal... (esto puede tardar unos segundos)

=== RESULTADOS DEL MODELO ===
Accauricy:  0.9626865671641791
Accuracy (Porcentaje de acierto): 96.27%

Matriz de Confusión:
[[ 57   3   0]
 [  7  85   0]
 [  0   0 116]]

DECISION TREE

In [6]:
from sklearn.tree import DecisionTreeClassifier

depth = []
accDT = []

for i in range(1,20):
    decision_tree = DecisionTreeClassifier(random_state=0, max_depth=i)
    # Entrenar modelo
    decision_tree.fit(X_train, y_train)
    # Hacer prediccion
    dt_pred = decision_tree.predict(X_test)
    # Accuracy
    dt_accuracy = accuracy_score(y_test, dt_pred)
    print("max_depth ",i,"Acc ",dt_accuracy)
    depth.append(i)
    accDT.append(dt_accuracy)
    
dt_accuracyMax = np.argmax(accDT)
print("Accuracy ",accDT[dt_accuracyMax], " with max_depth ",depth[dt_accuracyMax])

max_depth  1 Acc  0.7089552238805971
max_depth  2 Acc  0.832089552238806
max_depth  3 Acc  0.8582089552238806
max_depth  4 Acc  0.9216417910447762
max_depth  5 Acc  0.9402985074626866
max_depth  6 Acc  0.9514925373134329
max_depth  7 Acc  0.9589552238805971
max_depth  8 Acc  0.9664179104477612
max_depth  9 Acc  0.9626865671641791
max_depth  10 Acc  0.9626865671641791
max_depth  11 Acc  0.9626865671641791
max_depth  12 Acc  0.9589552238805971
max_depth  13 Acc  0.9589552238805971
max_depth  14 Acc  0.9589552238805971
max_depth  15 Acc  0.9589552238805971
max_depth  16 Acc  0.9589552238805971
max_depth  17 Acc  0.9589552238805971
max_depth  18 Acc  0.9589552238805971
max_depth  19 Acc  0.9589552238805971
Accuracy  0.9664179104477612  with max_depth  8

RANDOM FOREST

In [7]:
from sklearn.ensemble import RandomForestClassifier

# n_estimators = número de árboles de decisiones
clf = RandomForestClassifier(n_estimators=2000,max_depth=9, random_state=0) # construir
clf.fit(X_train, y_train)               # entrenar
y_predictRF = clf.predict(X_test)       # predecir

rf_accuracy = accuracy_score(y_test, y_predictRF)
print("accuracy",rf_accuracy)

accuracy 0.9776119402985075

KNN

In [8]:
from sklearn.neighbors import KNeighborsClassifier

ks = []                     # las k
acc = []                    # la accuaricy de cada k
knnPredictions = []         # las predicciones de cada k

# Probar k E [1, 20]
for i in range(1,20):
    
    # n_neighbors = la k del momento , metric = la metrica que quieras usar
    neigh = KNeighborsClassifier(n_neighbors=i, metric="manhattan")
    neigh.fit(X_train, y_train)                                 # entreno
    y_predictKNN = neigh.predict(X_test)                        # prediccion
    knn_accuracy = accuracy_score(y_test, y_predictKNN)         # accuaracy

    knnPredictions.append(y_predictKNN)
    ks.append(i)
    acc.append(knn_accuracy)
    print("K ",i,knn_accuracy)

knnAccuracyMax = np.argmax(acc)
print("Accuracy ",acc[knnAccuracyMax], " with K ",ks[knnAccuracyMax])

K  1 0.9402985074626866
K  2 0.9477611940298507
K  3 0.9552238805970149
K  4 0.9514925373134329
K  5 0.9477611940298507
K  6 0.9514925373134329
K  7 0.9477611940298507
K  8 0.9365671641791045
K  9 0.9514925373134329
K  10 0.9402985074626866
K  11 0.9440298507462687
K  12 0.9402985074626866
K  13 0.9402985074626866
K  14 0.9402985074626866
K  15 0.9365671641791045
K  16 0.9328358208955224
K  17 0.9402985074626866
K  18 0.9365671641791045
K  19 0.9402985074626866
Accuracy  0.9552238805970149  with K  3